[package]
name = "CodeDescriber"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
dirs = "3.0.2"
regex = "1.10.2"